//TODO: Remove //holdModelType column from routeModels and put it in holds
const routeModels = [
  {
    routeGrade: 'V0',
    //holdColor: 'White',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 0.85,
    positionY: 1.4,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 140,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#ededed',
    radius: 0.12,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V0',
    //holdColor: 'White',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 0.8,
    positionY: 1.9,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#ededed',
    radius: 0.12,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V0',
    //holdColor: 'White',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 1,
    positionY: 2.3,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 180,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#ededed',
    radius: 0.12,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V0',
    //holdColor: 'White',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 1.4,
    positionY: 2.8,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -10,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#ededed',
    radius: 0.12,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V0',
    //holdColor: 'White',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 0.85,
    positionY: 0.1,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#ededed',
    radius: 0.03
  },
  {
    routeGrade: 'V0',
    //holdColor: 'White',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 0.95,
    positionY: 0.5,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#ededed',
    radius: 0.03
  },
  {
    routeGrade: 'V0',
    //holdColor: 'White',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 0.2,
    positionY: 0.55,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#ededed',
    radius: 0.03
  },
  {
    routeGrade: 'V0',
    //holdColor: 'White',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 1.6,
    positionY: 1.4,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#ededed',
    radius: 0.03
  },
  {
    routeGrade: 'V0',
    //holdColor: 'White',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 1,
    positionY: 0.9,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 110,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#ededed',
    radius: 0.15,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V1',
    //holdColor: 'Yellow',
    holdType: 'sloper (sphere)',
    //holdModelType: 'a-sphere',
    positionX: 0.8,
    positionY: 2.1,
    positionZ: -0.95,
    rotationX: -20,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 2,
    roughness: 2,
    modelColor: '#fffe06',
    radius: 0.05,
    thetaLength: 360,
    thetaStart: 0
  },
  {
    routeGrade: 'V1',
    //holdColor: 'Yellow',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 1,
    positionY: 1.3,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#fffe06',
    radius: 0.03
  },
  {
    routeGrade: 'V1',
    //holdColor: 'Yellow',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 1.4,
    positionY: 1.1,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#fffe06',
    radius: 0.03
  },
  {
    routeGrade: 'V1',
    //holdColor: 'Yellow',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 1.3,
    positionY: 0.9,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#fffe06',
    radius: 0.03
  },
  {
    routeGrade: 'V1',
    //holdColor: 'Yellow',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 0.9,
    positionY: 0.5,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#fffe06',
    radius: 0.03
  },
  {
    routeGrade: 'V1',
    //holdColor: 'Yellow',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 0.9,
    positionY: 0.3,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#fffe06',
    radius: 0.03
  },
  {
    routeGrade: 'V1',
    //holdColor: 'Yellow',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 0.4,
    positionY: 0.6,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#fffe06',
    radius: 0.03
  },
  {
    routeGrade: 'V1',
    //holdColor: 'Yellow',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 1.1,
    positionY: 2.8,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -10,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#fffe06',
    radius: 0.06,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V1',
    //holdColor: 'Yellow',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 1.4,
    positionY: 2.3,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 20,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#fffe06',
    radius: 0.07,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V1',
    //holdColor: 'Yellow',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 0.4,
    positionY: 0.2,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#fffe06',
    radius: 0.03
  },
  {
    routeGrade: 'V1',
    //holdColor: 'Yellow',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 0.4,
    positionY: 1.1,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -20,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#fffe06',
    radius: 0.05,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V1',
    //holdColor: 'Yellow',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 0.3,
    positionY: 1.2,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -10,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#fffe06',
    radius: 0.05,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V1',
    //holdColor: 'Yellow',
    holdType: 'pocket',
    //holdModelType: 'a-torus',
    positionX: 0.8,
    positionY: 1.5,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 2,
    roughness: 2,
    modelColor: '#fffe06',
    radius: 0.13,
    radiusTubular: 0.025,
    arc: 360
  },
  {
    routeGrade: 'V1',
    //holdColor: 'Yellow',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 1.1,
    positionY: 1.8,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -30,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#fffe06',
    radius: 0.15,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V2',
    //holdColor: 'Green',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 1,
    positionY: 1.5,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#48ac10',
    radius: 0.03
  },
  {
    routeGrade: 'V2',
    //holdColor: 'Green',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 1,
    positionY: 0.5,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#48ac10',
    radius: 0.03
  },
  {
    routeGrade: 'V2',
    //holdColor: 'Green',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 1.3,
    positionY: 2.8,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -20,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.6,
    roughness: 2,
    modelColor: '#48ac10',
    radius: 0.08,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V2',
    //holdColor: 'Green',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 0.9,
    positionY: 2.4,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 70,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.6,
    roughness: 2,
    modelColor: '#48ac10',
    radius: 0.05,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V2',
    //holdColor: 'Green',
    holdType: 'pocket',
    //holdModelType: 'a-torus',
    positionX: 0.9,
    positionY: 2,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1.8,
    roughness: 2,
    modelColor: '#48ac10',
    radius: 0.05,
    radiusTubular: 0.009,
    arc: 360
  },
  {
    routeGrade: 'V2',
    //holdColor: 'Green',
    holdType: 'pocket',
    //holdModelType: 'a-torus',
    positionX: 1,
    positionY: 1.9,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1.8,
    roughness: 2,
    modelColor: '#48ac10',
    radius: 0.05,
    radiusTubular: 0.009,
    arc: 360
  },
  {
    routeGrade: 'V2',
    //holdColor: 'Green',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 0.48,
    positionY: 1.45,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -20,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#48ac10',
    radius: 0.06,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V2',
    //holdColor: 'Green',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 0.5,
    positionY: 1.3,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -20,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#48ac10',
    radius: 0.06,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V2',
    //holdColor: 'Green',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 1.1,
    positionY: 0.9,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#48ac10',
    radius: 0.03
  },
  {
    routeGrade: 'V3',
    //holdColor: 'Black',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 0.4,
    positionY: 1,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -90,
    scaleX: 1,
    scaleY: 1.5,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#565656',
    radius: 0.2,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V3',
    //holdColor: 'Black',
    holdType: 'sloper (sphere)',
    //holdModelType: 'a-sphere',
    positionX: 0.5,
    positionY: 1.3,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -20,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 2,
    roughness: 2,
    modelColor: '#565656',
    radius: 0.04,
    thetaLength: 360,
    thetaStart: 0
  },
  {
    routeGrade: 'V3',
    //holdColor: 'Black',
    holdType: 'sloper (sphere)',
    //holdModelType: 'a-sphere',
    positionX: 1.4,
    positionY: 1.2,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 20,
    scaleX: 1.4,
    scaleY: 1,
    scaleZ: 2,
    roughness: 2,
    modelColor: '#565656',
    radius: 0.05,
    thetaLength: 360,
    thetaStart: 0
  },
  {
    routeGrade: 'V3',
    //holdColor: 'Black',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 0.8,
    positionY: 1.9,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -20,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#565656',
    radius: 0.03,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V3',
    //holdColor: 'Black',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 1,
    positionY: 2.1,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 100,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#565656',
    radius: 0.15,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V3',
    //holdColor: 'Black',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 1.3,
    positionY: 2.6,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -20,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#565656',
    radius: 0.06,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V3',
    //holdColor: 'Black',
    holdType: 'sloper (sphere)',
    //holdModelType: 'a-sphere',
    positionX: 0.8,
    positionY: 2.7,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 2,
    roughness: 2,
    modelColor: '#565656',
    radius: 0.06,
    thetaLength: 360,
    thetaStart: 0
  },
  {
    routeGrade: 'V3',
    //holdColor: 'Black',
    holdType: 'sloper (sphere)',
    //holdModelType: 'a-sphere',
    positionX: 0.4,
    positionY: 3.1,
    positionZ: -0.95,
    rotationX: -30,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 2,
    roughness: 2,
    modelColor: '#565656',
    radius: 0.06,
    thetaLength: 360,
    thetaStart: 0
  },
  {
    routeGrade: 'V3',
    //holdColor: 'Black',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 0.2,
    positionY: 0.1,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#565656',
    radius: 0.03
  },
  {
    routeGrade: 'V3',
    //holdColor: 'Black',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 0.6,
    positionY: 0.13,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#565656',
    radius: 0.03
  },
  {
    routeGrade: 'V3',
    //holdColor: 'Black',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 1,
    positionY: 0.5,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#565656',
    radius: 0.03
  },
  {
    routeGrade: 'V3',
    //holdColor: 'Black',
    holdType: 'sloper (sphere)',
    //holdModelType: 'a-sphere',
    positionX: 0.4,
    positionY: 0.7,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -30,
    scaleX: 1,
    scaleY: 0.6,
    scaleZ: 2,
    roughness: 2,
    modelColor: '#565656',
    radius: 0.08,
    thetaLength: 360,
    thetaStart: 0
  },
  {
    routeGrade: 'V3',
    //holdColor: 'Black',
    holdType: 'sloper (sphere)',
    //holdModelType: 'a-sphere',
    positionX: 1.3,
    positionY: 1,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 2,
    roughness: 2,
    modelColor: '#565656',
    radius: 0.05,
    thetaLength: 360,
    thetaStart: 0
  },
  {
    routeGrade: 'V3',
    //holdColor: 'Black',
    holdType: 'sloper (sphere)',
    //holdModelType: 'a-sphere',
    positionX: 0.6,
    positionY: 1.55,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 40,
    scaleX: 2,
    scaleY: 1,
    scaleZ: 2,
    roughness: 2,
    modelColor: '#565656',
    radius: 0.06,
    thetaLength: 360,
    thetaStart: 0
  },
  {
    routeGrade: 'V5',
    //holdColor: 'Purple',
    holdType: 'sloper (box)',
    //holdModelType: 'a-box',
    positionX: 0.5,
    positionY: 2.2,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 2,
    roughness: 2,
    modelColor: '#531b93',
    depth: 0.2,
    height: 0.3,
    width: 0.2
  },
  {
    routeGrade: 'V5',
    //holdColor: 'Purple',
    holdType: 'sloper (box)',
    //holdModelType: 'a-box',
    positionX: 1.5,
    positionY: 2.2,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 2,
    roughness: 2,
    modelColor: '#531b93',
    depth: 0.2,
    height: 0.4,
    width: 0.2
  },
  {
    routeGrade: 'V5',
    //holdColor: 'Purple',
    holdType: 'pinch',
    //holdModelType: 'a-box',
    positionX: 2,
    positionY: 2.8,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#531b93',
    depth: 0.05,
    height: 0.1,
    width: 0.15
  },
  {
    routeGrade: 'V5',
    //holdColor: 'Purple',
    holdType: 'pinch',
    //holdModelType: 'a-box',
    positionX: 2,
    positionY: 3,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#531b93',
    depth: 0.05,
    height: 0.1,
    width: 0.15
  },
  {
    routeGrade: 'V5',
    //holdColor: 'Purple',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 1.2,
    positionY: 0.2,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    radius: 0.03,
    modelColor: '#531b93'
  },
  {
    routeGrade: 'V5',
    //holdColor: 'Purple',
    holdType: 'footHold',
    //holdModelType: 'a-octahedron',
    positionX: 0.8,
    positionY: 0.7,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1.5,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    radius: 0.03,
    modelColor: '#531b93'
  },
  {
    routeGrade: 'V5',
    //holdColor: 'Purple',
    holdType: 'jug',
    //holdModelType: 'a-sphere',
    positionX: 1,
    positionY: 1.2,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 0.8,
    roughness: 2,
    modelColor: '#531b93',
    radius: 0.25,
    thetaLength: 120,
    thetaStart: 90
  },
  {
    routeGrade: 'V4',
    //holdColor: 'Green',
    holdType: 'pinch',
    //holdModelType: 'a-box',
    positionX: 1.4,
    positionY: 0.5,
    positionZ: -0.95,
    rotationX: 30,
    rotationY: 0,
    rotationZ: -30,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#48ac10',
    depth: 0.05,
    height: 0.2,
    width: 0.1
  },
  {
    routeGrade: 'V4',
    //holdColor: 'Green',
    holdType: 'pinch',
    //holdModelType: 'a-box',
    positionX: 1.2,
    positionY: 0.6,
    positionZ: -0.95,
    rotationX: 30,
    rotationY: 0,
    rotationZ: -30,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#48ac10',
    depth: 0.05,
    height: 0.2,
    width: 0.1
  },
  {
    routeGrade: 'V4',
    //holdColor: 'Green',
    holdType: 'pinch',
    //holdModelType: 'a-box',
    positionX: 1,
    positionY: 1,
    positionZ: -0.95,
    rotationX: 35,
    rotationY: 0,
    rotationZ: 30,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#48ac10',
    depth: 0.05,
    height: 0.2,
    width: 0.1
  },
  {
    routeGrade: 'V4',
    //holdColor: 'Green',
    holdType: 'pinch',
    //holdModelType: 'a-box',
    positionX: 1,
    positionY: 1.3,
    positionZ: -0.95,
    rotationX: 35,
    rotationY: 0,
    rotationZ: 30,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#48ac10',
    depth: 0.05,
    height: 0.2,
    width: 0.1
  },
  {
    routeGrade: 'V4',
    //holdColor: 'Green',
    holdType: 'pinch',
    //holdModelType: 'a-box',
    positionX: 0.95,
    positionY: 1.5,
    positionZ: -0.95,
    rotationX: 30,
    rotationY: 0,
    rotationZ: 40,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#48ac10',
    depth: 0.05,
    height: 0.1,
    width: 0.05
  },
  {
    routeGrade: 'V4',
    //holdColor: 'Green',
    holdType: 'pinch',
    //holdModelType: 'a-box',
    positionX: 0.6,
    positionY: 1.9,
    positionZ: -0.95,
    rotationX: 30,
    rotationY: 0,
    rotationZ: -30,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#48ac10',
    depth: 0.05,
    height: 0.2,
    width: 0.1
  },
  {
    routeGrade: 'V4',
    //holdColor: 'Green',
    holdType: 'pinch',
    //holdModelType: 'a-box',
    positionX: 1.4,
    positionY: 1.9,
    positionZ: -0.95,
    rotationX: 35,
    rotationY: 0,
    rotationZ: 30,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#48ac10',
    depth: 0.05,
    height: 0.2,
    width: 0.1
  },
  {
    routeGrade: 'V4',
    //holdColor: 'Green',
    holdType: 'sloper (sphere)',
    //holdModelType: 'a-sphere',
    positionX: 0.5,
    positionY: 2.3,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 30,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 2,
    roughness: 2,
    radius: 0.08,
    modelColor: '#48ac10',
    thetaLength: 360,
    thetaStart: 0
  },
  {
    routeGrade: 'V4',
    //holdColor: 'Green',
    holdType: 'pinch',
    //holdModelType: 'a-box',
    positionX: 1.3,
    positionY: 2.3,
    positionZ: -0.95,
    rotationX: 35,
    rotationY: 0,
    rotationZ: 30,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#48ac10',
    depth: 0.05,
    height: 0.1,
    width: 0.05
  },
  {
    routeGrade: 'V4',
    //holdColor: 'Green',
    holdType: 'pinch',
    //holdModelType: 'a-box',
    positionX: 0.4,
    positionY: 2.6,
    positionZ: -0.95,
    rotationX: 35,
    rotationY: 0,
    rotationZ: -30,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 1,
    roughness: 2,
    modelColor: '#48ac10',
    depth: 0.05,
    height: 0.2,
    width: 0.1
  },
  {
    routeGrade: 'V4',
    //holdColor: 'Green',
    holdType: 'sloper (sphere)',
    //holdModelType: 'a-sphere',
    positionX: 0.9,
    positionY: 3.1,
    positionZ: -0.95,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    scaleX: 1,
    scaleY: 1,
    scaleZ: 2,
    roughness: 2,
    radius: 0.08,
    modelColor: '#48ac10',
    thetaLength: 360,
    thetaStart: 0
  }
];

module.exports = { routeModels };
